namespace APP.FROMS.Telas
{
    partial class registrarProdutocs
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(registrarProdutocs));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.lbl_cadastrodeProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnEnviar_registroProd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtboxNome_RegistroProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtboxDescricao_RegistroProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtboxPreco_RegistroProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtboxQntd_RegistroProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtboxCategoria_registroProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblNome_RegistroProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblDescrição_RegistroProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPreco_RegistroProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblQntd_RegistroProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblCategoria_Registroprod = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtboxID_RegistrarProd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblID_RegistrarProd = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnCarcelar_Registroprod = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.SuspendLayout();
            // 
            // lbl_cadastrodeProd
            // 
            this.lbl_cadastrodeProd.AllowParentOverrides = false;
            this.lbl_cadastrodeProd.AutoEllipsis = false;
            this.lbl_cadastrodeProd.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_cadastrodeProd.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_cadastrodeProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 12F, System.Drawing.FontStyle.Bold);
            this.lbl_cadastrodeProd.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lbl_cadastrodeProd.Location = new System.Drawing.Point(131, 27);
            this.lbl_cadastrodeProd.Name = "lbl_cadastrodeProd";
            this.lbl_cadastrodeProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_cadastrodeProd.Size = new System.Drawing.Size(542, 27);
            this.lbl_cadastrodeProd.TabIndex = 1;
            this.lbl_cadastrodeProd.Text = "Cadastre o novo produto passando  os daddos abaixo:";
            this.lbl_cadastrodeProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_cadastrodeProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lbl_cadastrodeProd.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // btnEnviar_registroProd
            // 
            this.btnEnviar_registroProd.AllowAnimations = true;
            this.btnEnviar_registroProd.AllowMouseEffects = true;
            this.btnEnviar_registroProd.AllowToggling = false;
            this.btnEnviar_registroProd.AnimationSpeed = 200;
            this.btnEnviar_registroProd.AutoGenerateColors = false;
            this.btnEnviar_registroProd.AutoRoundBorders = true;
            this.btnEnviar_registroProd.AutoSizeLeftIcon = true;
            this.btnEnviar_registroProd.AutoSizeRightIcon = true;
            this.btnEnviar_registroProd.BackColor = System.Drawing.Color.Transparent;
            this.btnEnviar_registroProd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEnviar_registroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEnviar_registroProd.BackgroundImage")));
            this.btnEnviar_registroProd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEnviar_registroProd.ButtonText = "Enviar";
            this.btnEnviar_registroProd.ButtonTextMarginLeft = 0;
            this.btnEnviar_registroProd.ColorContrastOnClick = 45;
            this.btnEnviar_registroProd.ColorContrastOnHover = 45;
            this.btnEnviar_registroProd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnEnviar_registroProd.CustomizableEdges = borderEdges1;
            this.btnEnviar_registroProd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEnviar_registroProd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEnviar_registroProd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEnviar_registroProd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEnviar_registroProd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnEnviar_registroProd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEnviar_registroProd.ForeColor = System.Drawing.Color.White;
            this.btnEnviar_registroProd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEnviar_registroProd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEnviar_registroProd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEnviar_registroProd.IconMarginLeft = 11;
            this.btnEnviar_registroProd.IconPadding = 10;
            this.btnEnviar_registroProd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEnviar_registroProd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEnviar_registroProd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEnviar_registroProd.IconSize = 25;
            this.btnEnviar_registroProd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEnviar_registroProd.IdleBorderRadius = 36;
            this.btnEnviar_registroProd.IdleBorderThickness = 1;
            this.btnEnviar_registroProd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEnviar_registroProd.IdleIconLeftImage = null;
            this.btnEnviar_registroProd.IdleIconRightImage = null;
            this.btnEnviar_registroProd.IndicateFocus = false;
            this.btnEnviar_registroProd.Location = new System.Drawing.Point(715, 400);
            this.btnEnviar_registroProd.Name = "btnEnviar_registroProd";
            this.btnEnviar_registroProd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEnviar_registroProd.OnDisabledState.BorderRadius = 1;
            this.btnEnviar_registroProd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEnviar_registroProd.OnDisabledState.BorderThickness = 1;
            this.btnEnviar_registroProd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEnviar_registroProd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEnviar_registroProd.OnDisabledState.IconLeftImage = null;
            this.btnEnviar_registroProd.OnDisabledState.IconRightImage = null;
            this.btnEnviar_registroProd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEnviar_registroProd.onHoverState.BorderRadius = 1;
            this.btnEnviar_registroProd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEnviar_registroProd.onHoverState.BorderThickness = 1;
            this.btnEnviar_registroProd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEnviar_registroProd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEnviar_registroProd.onHoverState.IconLeftImage = null;
            this.btnEnviar_registroProd.onHoverState.IconRightImage = null;
            this.btnEnviar_registroProd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEnviar_registroProd.OnIdleState.BorderRadius = 1;
            this.btnEnviar_registroProd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEnviar_registroProd.OnIdleState.BorderThickness = 1;
            this.btnEnviar_registroProd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEnviar_registroProd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEnviar_registroProd.OnIdleState.IconLeftImage = null;
            this.btnEnviar_registroProd.OnIdleState.IconRightImage = null;
            this.btnEnviar_registroProd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEnviar_registroProd.OnPressedState.BorderRadius = 1;
            this.btnEnviar_registroProd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEnviar_registroProd.OnPressedState.BorderThickness = 1;
            this.btnEnviar_registroProd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEnviar_registroProd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEnviar_registroProd.OnPressedState.IconLeftImage = null;
            this.btnEnviar_registroProd.OnPressedState.IconRightImage = null;
            this.btnEnviar_registroProd.Size = new System.Drawing.Size(73, 38);
            this.btnEnviar_registroProd.TabIndex = 3;
            this.btnEnviar_registroProd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEnviar_registroProd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEnviar_registroProd.TextMarginLeft = 0;
            this.btnEnviar_registroProd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEnviar_registroProd.UseDefaultRadiusAndThickness = true;
            this.btnEnviar_registroProd.Click += new System.EventHandler(this.btnEnviar_registroProd_Click);
            // 
            // txtboxNome_RegistroProd
            // 
            this.txtboxNome_RegistroProd.AcceptsReturn = false;
            this.txtboxNome_RegistroProd.AcceptsTab = false;
            this.txtboxNome_RegistroProd.AnimationSpeed = 200;
            this.txtboxNome_RegistroProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxNome_RegistroProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxNome_RegistroProd.AutoSizeHeight = true;
            this.txtboxNome_RegistroProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxNome_RegistroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxNome_RegistroProd.BackgroundImage")));
            this.txtboxNome_RegistroProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxNome_RegistroProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxNome_RegistroProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxNome_RegistroProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxNome_RegistroProd.BorderRadius = 1;
            this.txtboxNome_RegistroProd.BorderThickness = 1;
            this.txtboxNome_RegistroProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxNome_RegistroProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxNome_RegistroProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxNome_RegistroProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxNome_RegistroProd.DefaultText = "";
            this.txtboxNome_RegistroProd.FillColor = System.Drawing.Color.White;
            this.txtboxNome_RegistroProd.HideSelection = true;
            this.txtboxNome_RegistroProd.IconLeft = null;
            this.txtboxNome_RegistroProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxNome_RegistroProd.IconPadding = 10;
            this.txtboxNome_RegistroProd.IconRight = null;
            this.txtboxNome_RegistroProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxNome_RegistroProd.Lines = new string[0];
            this.txtboxNome_RegistroProd.Location = new System.Drawing.Point(258, 154);
            this.txtboxNome_RegistroProd.MaxLength = 32767;
            this.txtboxNome_RegistroProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxNome_RegistroProd.Modified = false;
            this.txtboxNome_RegistroProd.Multiline = false;
            this.txtboxNome_RegistroProd.Name = "txtboxNome_RegistroProd";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxNome_RegistroProd.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxNome_RegistroProd.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxNome_RegistroProd.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxNome_RegistroProd.OnIdleState = stateProperties4;
            this.txtboxNome_RegistroProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxNome_RegistroProd.PasswordChar = '\0';
            this.txtboxNome_RegistroProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxNome_RegistroProd.PlaceholderText = "Enter text";
            this.txtboxNome_RegistroProd.ReadOnly = false;
            this.txtboxNome_RegistroProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxNome_RegistroProd.SelectedText = "";
            this.txtboxNome_RegistroProd.SelectionLength = 0;
            this.txtboxNome_RegistroProd.SelectionStart = 0;
            this.txtboxNome_RegistroProd.ShortcutsEnabled = true;
            this.txtboxNome_RegistroProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxNome_RegistroProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxNome_RegistroProd.TabIndex = 7;
            this.txtboxNome_RegistroProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxNome_RegistroProd.TextMarginBottom = 0;
            this.txtboxNome_RegistroProd.TextMarginLeft = 3;
            this.txtboxNome_RegistroProd.TextMarginTop = 1;
            this.txtboxNome_RegistroProd.TextPlaceholder = "Enter text";
            this.txtboxNome_RegistroProd.UseSystemPasswordChar = false;
            this.txtboxNome_RegistroProd.WordWrap = true;
            this.txtboxNome_RegistroProd.TextChanged += new System.EventHandler(this.txtboxNome_RegistroProd_TextChanged);
            // 
            // txtboxDescricao_RegistroProd
            // 
            this.txtboxDescricao_RegistroProd.AcceptsReturn = false;
            this.txtboxDescricao_RegistroProd.AcceptsTab = false;
            this.txtboxDescricao_RegistroProd.AnimationSpeed = 200;
            this.txtboxDescricao_RegistroProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxDescricao_RegistroProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxDescricao_RegistroProd.AutoSizeHeight = true;
            this.txtboxDescricao_RegistroProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxDescricao_RegistroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxDescricao_RegistroProd.BackgroundImage")));
            this.txtboxDescricao_RegistroProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxDescricao_RegistroProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxDescricao_RegistroProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxDescricao_RegistroProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxDescricao_RegistroProd.BorderRadius = 1;
            this.txtboxDescricao_RegistroProd.BorderThickness = 1;
            this.txtboxDescricao_RegistroProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxDescricao_RegistroProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxDescricao_RegistroProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxDescricao_RegistroProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxDescricao_RegistroProd.DefaultText = "";
            this.txtboxDescricao_RegistroProd.FillColor = System.Drawing.Color.White;
            this.txtboxDescricao_RegistroProd.HideSelection = true;
            this.txtboxDescricao_RegistroProd.IconLeft = null;
            this.txtboxDescricao_RegistroProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxDescricao_RegistroProd.IconPadding = 10;
            this.txtboxDescricao_RegistroProd.IconRight = null;
            this.txtboxDescricao_RegistroProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxDescricao_RegistroProd.Lines = new string[0];
            this.txtboxDescricao_RegistroProd.Location = new System.Drawing.Point(267, 214);
            this.txtboxDescricao_RegistroProd.MaxLength = 32767;
            this.txtboxDescricao_RegistroProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxDescricao_RegistroProd.Modified = false;
            this.txtboxDescricao_RegistroProd.Multiline = false;
            this.txtboxDescricao_RegistroProd.Name = "txtboxDescricao_RegistroProd";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxDescricao_RegistroProd.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxDescricao_RegistroProd.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxDescricao_RegistroProd.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxDescricao_RegistroProd.OnIdleState = stateProperties8;
            this.txtboxDescricao_RegistroProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxDescricao_RegistroProd.PasswordChar = '\0';
            this.txtboxDescricao_RegistroProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxDescricao_RegistroProd.PlaceholderText = "Enter text";
            this.txtboxDescricao_RegistroProd.ReadOnly = false;
            this.txtboxDescricao_RegistroProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxDescricao_RegistroProd.SelectedText = "";
            this.txtboxDescricao_RegistroProd.SelectionLength = 0;
            this.txtboxDescricao_RegistroProd.SelectionStart = 0;
            this.txtboxDescricao_RegistroProd.ShortcutsEnabled = true;
            this.txtboxDescricao_RegistroProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxDescricao_RegistroProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxDescricao_RegistroProd.TabIndex = 8;
            this.txtboxDescricao_RegistroProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxDescricao_RegistroProd.TextMarginBottom = 0;
            this.txtboxDescricao_RegistroProd.TextMarginLeft = 3;
            this.txtboxDescricao_RegistroProd.TextMarginTop = 1;
            this.txtboxDescricao_RegistroProd.TextPlaceholder = "Enter text";
            this.txtboxDescricao_RegistroProd.UseSystemPasswordChar = false;
            this.txtboxDescricao_RegistroProd.WordWrap = true;
            this.txtboxDescricao_RegistroProd.TextChanged += new System.EventHandler(this.txtbox_RegistroProd_TextChanged);
            // 
            // txtboxPreco_RegistroProd
            // 
            this.txtboxPreco_RegistroProd.AcceptsReturn = false;
            this.txtboxPreco_RegistroProd.AcceptsTab = false;
            this.txtboxPreco_RegistroProd.AnimationSpeed = 200;
            this.txtboxPreco_RegistroProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxPreco_RegistroProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxPreco_RegistroProd.AutoSizeHeight = true;
            this.txtboxPreco_RegistroProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxPreco_RegistroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxPreco_RegistroProd.BackgroundImage")));
            this.txtboxPreco_RegistroProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxPreco_RegistroProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxPreco_RegistroProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxPreco_RegistroProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxPreco_RegistroProd.BorderRadius = 1;
            this.txtboxPreco_RegistroProd.BorderThickness = 1;
            this.txtboxPreco_RegistroProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxPreco_RegistroProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxPreco_RegistroProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxPreco_RegistroProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxPreco_RegistroProd.DefaultText = "";
            this.txtboxPreco_RegistroProd.FillColor = System.Drawing.Color.White;
            this.txtboxPreco_RegistroProd.HideSelection = true;
            this.txtboxPreco_RegistroProd.IconLeft = null;
            this.txtboxPreco_RegistroProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxPreco_RegistroProd.IconPadding = 10;
            this.txtboxPreco_RegistroProd.IconRight = null;
            this.txtboxPreco_RegistroProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxPreco_RegistroProd.Lines = new string[0];
            this.txtboxPreco_RegistroProd.Location = new System.Drawing.Point(267, 276);
            this.txtboxPreco_RegistroProd.MaxLength = 32767;
            this.txtboxPreco_RegistroProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxPreco_RegistroProd.Modified = false;
            this.txtboxPreco_RegistroProd.Multiline = false;
            this.txtboxPreco_RegistroProd.Name = "txtboxPreco_RegistroProd";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxPreco_RegistroProd.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxPreco_RegistroProd.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxPreco_RegistroProd.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxPreco_RegistroProd.OnIdleState = stateProperties12;
            this.txtboxPreco_RegistroProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxPreco_RegistroProd.PasswordChar = '\0';
            this.txtboxPreco_RegistroProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxPreco_RegistroProd.PlaceholderText = "Enter text";
            this.txtboxPreco_RegistroProd.ReadOnly = false;
            this.txtboxPreco_RegistroProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxPreco_RegistroProd.SelectedText = "";
            this.txtboxPreco_RegistroProd.SelectionLength = 0;
            this.txtboxPreco_RegistroProd.SelectionStart = 0;
            this.txtboxPreco_RegistroProd.ShortcutsEnabled = true;
            this.txtboxPreco_RegistroProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxPreco_RegistroProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxPreco_RegistroProd.TabIndex = 9;
            this.txtboxPreco_RegistroProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxPreco_RegistroProd.TextMarginBottom = 0;
            this.txtboxPreco_RegistroProd.TextMarginLeft = 3;
            this.txtboxPreco_RegistroProd.TextMarginTop = 1;
            this.txtboxPreco_RegistroProd.TextPlaceholder = "Enter text";
            this.txtboxPreco_RegistroProd.UseSystemPasswordChar = false;
            this.txtboxPreco_RegistroProd.WordWrap = true;
            this.txtboxPreco_RegistroProd.TextChanged += new System.EventHandler(this.textboxPreco_RegistroProd_TextChanged);
            // 
            // txtboxQntd_RegistroProd
            // 
            this.txtboxQntd_RegistroProd.AcceptsReturn = false;
            this.txtboxQntd_RegistroProd.AcceptsTab = false;
            this.txtboxQntd_RegistroProd.AnimationSpeed = 200;
            this.txtboxQntd_RegistroProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxQntd_RegistroProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxQntd_RegistroProd.AutoSizeHeight = true;
            this.txtboxQntd_RegistroProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxQntd_RegistroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxQntd_RegistroProd.BackgroundImage")));
            this.txtboxQntd_RegistroProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxQntd_RegistroProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxQntd_RegistroProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxQntd_RegistroProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxQntd_RegistroProd.BorderRadius = 1;
            this.txtboxQntd_RegistroProd.BorderThickness = 1;
            this.txtboxQntd_RegistroProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxQntd_RegistroProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxQntd_RegistroProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxQntd_RegistroProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxQntd_RegistroProd.DefaultText = "";
            this.txtboxQntd_RegistroProd.FillColor = System.Drawing.Color.White;
            this.txtboxQntd_RegistroProd.HideSelection = true;
            this.txtboxQntd_RegistroProd.IconLeft = null;
            this.txtboxQntd_RegistroProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxQntd_RegistroProd.IconPadding = 10;
            this.txtboxQntd_RegistroProd.IconRight = null;
            this.txtboxQntd_RegistroProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxQntd_RegistroProd.Lines = new string[0];
            this.txtboxQntd_RegistroProd.Location = new System.Drawing.Point(267, 338);
            this.txtboxQntd_RegistroProd.MaxLength = 32767;
            this.txtboxQntd_RegistroProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxQntd_RegistroProd.Modified = false;
            this.txtboxQntd_RegistroProd.Multiline = false;
            this.txtboxQntd_RegistroProd.Name = "txtboxQntd_RegistroProd";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxQntd_RegistroProd.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxQntd_RegistroProd.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxQntd_RegistroProd.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxQntd_RegistroProd.OnIdleState = stateProperties16;
            this.txtboxQntd_RegistroProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxQntd_RegistroProd.PasswordChar = '\0';
            this.txtboxQntd_RegistroProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxQntd_RegistroProd.PlaceholderText = "Enter text";
            this.txtboxQntd_RegistroProd.ReadOnly = false;
            this.txtboxQntd_RegistroProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxQntd_RegistroProd.SelectedText = "";
            this.txtboxQntd_RegistroProd.SelectionLength = 0;
            this.txtboxQntd_RegistroProd.SelectionStart = 0;
            this.txtboxQntd_RegistroProd.ShortcutsEnabled = true;
            this.txtboxQntd_RegistroProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxQntd_RegistroProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxQntd_RegistroProd.TabIndex = 10;
            this.txtboxQntd_RegistroProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxQntd_RegistroProd.TextMarginBottom = 0;
            this.txtboxQntd_RegistroProd.TextMarginLeft = 3;
            this.txtboxQntd_RegistroProd.TextMarginTop = 1;
            this.txtboxQntd_RegistroProd.TextPlaceholder = "Enter text";
            this.txtboxQntd_RegistroProd.UseSystemPasswordChar = false;
            this.txtboxQntd_RegistroProd.WordWrap = true;
            this.txtboxQntd_RegistroProd.TextChanged += new System.EventHandler(this.txtboxQntd_RegistroProd_TextChanged);
            // 
            // txtboxCategoria_registroProd
            // 
            this.txtboxCategoria_registroProd.AcceptsReturn = false;
            this.txtboxCategoria_registroProd.AcceptsTab = false;
            this.txtboxCategoria_registroProd.AnimationSpeed = 200;
            this.txtboxCategoria_registroProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxCategoria_registroProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxCategoria_registroProd.AutoSizeHeight = true;
            this.txtboxCategoria_registroProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxCategoria_registroProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxCategoria_registroProd.BackgroundImage")));
            this.txtboxCategoria_registroProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxCategoria_registroProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxCategoria_registroProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxCategoria_registroProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxCategoria_registroProd.BorderRadius = 1;
            this.txtboxCategoria_registroProd.BorderThickness = 1;
            this.txtboxCategoria_registroProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxCategoria_registroProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxCategoria_registroProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxCategoria_registroProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxCategoria_registroProd.DefaultText = "";
            this.txtboxCategoria_registroProd.FillColor = System.Drawing.Color.White;
            this.txtboxCategoria_registroProd.HideSelection = true;
            this.txtboxCategoria_registroProd.IconLeft = null;
            this.txtboxCategoria_registroProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxCategoria_registroProd.IconPadding = 10;
            this.txtboxCategoria_registroProd.IconRight = null;
            this.txtboxCategoria_registroProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxCategoria_registroProd.Lines = new string[0];
            this.txtboxCategoria_registroProd.Location = new System.Drawing.Point(267, 400);
            this.txtboxCategoria_registroProd.MaxLength = 32767;
            this.txtboxCategoria_registroProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxCategoria_registroProd.Modified = false;
            this.txtboxCategoria_registroProd.Multiline = false;
            this.txtboxCategoria_registroProd.Name = "txtboxCategoria_registroProd";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxCategoria_registroProd.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxCategoria_registroProd.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxCategoria_registroProd.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxCategoria_registroProd.OnIdleState = stateProperties20;
            this.txtboxCategoria_registroProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxCategoria_registroProd.PasswordChar = '\0';
            this.txtboxCategoria_registroProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxCategoria_registroProd.PlaceholderText = "Enter text";
            this.txtboxCategoria_registroProd.ReadOnly = false;
            this.txtboxCategoria_registroProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxCategoria_registroProd.SelectedText = "";
            this.txtboxCategoria_registroProd.SelectionLength = 0;
            this.txtboxCategoria_registroProd.SelectionStart = 0;
            this.txtboxCategoria_registroProd.ShortcutsEnabled = true;
            this.txtboxCategoria_registroProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxCategoria_registroProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxCategoria_registroProd.TabIndex = 11;
            this.txtboxCategoria_registroProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxCategoria_registroProd.TextMarginBottom = 0;
            this.txtboxCategoria_registroProd.TextMarginLeft = 3;
            this.txtboxCategoria_registroProd.TextMarginTop = 1;
            this.txtboxCategoria_registroProd.TextPlaceholder = "Enter text";
            this.txtboxCategoria_registroProd.UseSystemPasswordChar = false;
            this.txtboxCategoria_registroProd.WordWrap = true;
            this.txtboxCategoria_registroProd.TextChanged += new System.EventHandler(this.txtboxCategoria_registroProd_TextChanged);
            // 
            // lblNome_RegistroProd
            // 
            this.lblNome_RegistroProd.AllowParentOverrides = false;
            this.lblNome_RegistroProd.AutoEllipsis = false;
            this.lblNome_RegistroProd.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblNome_RegistroProd.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblNome_RegistroProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblNome_RegistroProd.Location = new System.Drawing.Point(267, 127);
            this.lblNome_RegistroProd.Name = "lblNome_RegistroProd";
            this.lblNome_RegistroProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblNome_RegistroProd.Size = new System.Drawing.Size(51, 19);
            this.lblNome_RegistroProd.TabIndex = 13;
            this.lblNome_RegistroProd.Text = "Nome:";
            this.lblNome_RegistroProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblNome_RegistroProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblNome_RegistroProd.Click += new System.EventHandler(this.bunifuLabel1_Click_1);
            // 
            // lblDescrição_RegistroProd
            // 
            this.lblDescrição_RegistroProd.AllowParentOverrides = false;
            this.lblDescrição_RegistroProd.AutoEllipsis = false;
            this.lblDescrição_RegistroProd.CursorType = null;
            this.lblDescrição_RegistroProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblDescrição_RegistroProd.Location = new System.Drawing.Point(267, 189);
            this.lblDescrição_RegistroProd.Name = "lblDescrição_RegistroProd";
            this.lblDescrição_RegistroProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDescrição_RegistroProd.Size = new System.Drawing.Size(73, 19);
            this.lblDescrição_RegistroProd.TabIndex = 14;
            this.lblDescrição_RegistroProd.Text = "Descrição";
            this.lblDescrição_RegistroProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDescrição_RegistroProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblDescrição_RegistroProd.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // lblPreco_RegistroProd
            // 
            this.lblPreco_RegistroProd.AllowParentOverrides = false;
            this.lblPreco_RegistroProd.AutoEllipsis = false;
            this.lblPreco_RegistroProd.CursorType = null;
            this.lblPreco_RegistroProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblPreco_RegistroProd.Location = new System.Drawing.Point(267, 251);
            this.lblPreco_RegistroProd.Name = "lblPreco_RegistroProd";
            this.lblPreco_RegistroProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPreco_RegistroProd.Size = new System.Drawing.Size(43, 19);
            this.lblPreco_RegistroProd.TabIndex = 15;
            this.lblPreco_RegistroProd.Text = "Preço";
            this.lblPreco_RegistroProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPreco_RegistroProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblPreco_RegistroProd.Click += new System.EventHandler(this.btnPreco_RegistroProd_Click);
            // 
            // lblQntd_RegistroProd
            // 
            this.lblQntd_RegistroProd.AllowParentOverrides = false;
            this.lblQntd_RegistroProd.AutoEllipsis = false;
            this.lblQntd_RegistroProd.CursorType = null;
            this.lblQntd_RegistroProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblQntd_RegistroProd.Location = new System.Drawing.Point(267, 313);
            this.lblQntd_RegistroProd.Name = "lblQntd_RegistroProd";
            this.lblQntd_RegistroProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblQntd_RegistroProd.Size = new System.Drawing.Size(93, 19);
            this.lblQntd_RegistroProd.TabIndex = 16;
            this.lblQntd_RegistroProd.Text = "Quantidade:";
            this.lblQntd_RegistroProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblQntd_RegistroProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblQntd_RegistroProd.Click += new System.EventHandler(this.lblQntd_RegistroProd_Click);
            // 
            // lblCategoria_Registroprod
            // 
            this.lblCategoria_Registroprod.AllowParentOverrides = false;
            this.lblCategoria_Registroprod.AutoEllipsis = false;
            this.lblCategoria_Registroprod.CursorType = null;
            this.lblCategoria_Registroprod.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCategoria_Registroprod.Location = new System.Drawing.Point(267, 375);
            this.lblCategoria_Registroprod.Name = "lblCategoria_Registroprod";
            this.lblCategoria_Registroprod.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCategoria_Registroprod.Size = new System.Drawing.Size(73, 19);
            this.lblCategoria_Registroprod.TabIndex = 17;
            this.lblCategoria_Registroprod.Text = "Categoria";
            this.lblCategoria_Registroprod.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCategoria_Registroprod.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblCategoria_Registroprod.Click += new System.EventHandler(this.lblCategoria_Registroprod_Click);
            // 
            // txtboxID_RegistrarProd
            // 
            this.txtboxID_RegistrarProd.AcceptsReturn = false;
            this.txtboxID_RegistrarProd.AcceptsTab = false;
            this.txtboxID_RegistrarProd.AnimationSpeed = 200;
            this.txtboxID_RegistrarProd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtboxID_RegistrarProd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtboxID_RegistrarProd.AutoSizeHeight = true;
            this.txtboxID_RegistrarProd.BackColor = System.Drawing.Color.Transparent;
            this.txtboxID_RegistrarProd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtboxID_RegistrarProd.BackgroundImage")));
            this.txtboxID_RegistrarProd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtboxID_RegistrarProd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtboxID_RegistrarProd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtboxID_RegistrarProd.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtboxID_RegistrarProd.BorderRadius = 1;
            this.txtboxID_RegistrarProd.BorderThickness = 1;
            this.txtboxID_RegistrarProd.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtboxID_RegistrarProd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtboxID_RegistrarProd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxID_RegistrarProd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtboxID_RegistrarProd.DefaultText = "";
            this.txtboxID_RegistrarProd.FillColor = System.Drawing.Color.White;
            this.txtboxID_RegistrarProd.HideSelection = true;
            this.txtboxID_RegistrarProd.IconLeft = null;
            this.txtboxID_RegistrarProd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxID_RegistrarProd.IconPadding = 10;
            this.txtboxID_RegistrarProd.IconRight = null;
            this.txtboxID_RegistrarProd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtboxID_RegistrarProd.Lines = new string[0];
            this.txtboxID_RegistrarProd.Location = new System.Drawing.Point(258, 90);
            this.txtboxID_RegistrarProd.MaxLength = 32767;
            this.txtboxID_RegistrarProd.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtboxID_RegistrarProd.Modified = false;
            this.txtboxID_RegistrarProd.Multiline = false;
            this.txtboxID_RegistrarProd.Name = "txtboxID_RegistrarProd";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxID_RegistrarProd.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtboxID_RegistrarProd.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxID_RegistrarProd.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtboxID_RegistrarProd.OnIdleState = stateProperties24;
            this.txtboxID_RegistrarProd.Padding = new System.Windows.Forms.Padding(3);
            this.txtboxID_RegistrarProd.PasswordChar = '\0';
            this.txtboxID_RegistrarProd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtboxID_RegistrarProd.PlaceholderText = "Enter text";
            this.txtboxID_RegistrarProd.ReadOnly = false;
            this.txtboxID_RegistrarProd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtboxID_RegistrarProd.SelectedText = "";
            this.txtboxID_RegistrarProd.SelectionLength = 0;
            this.txtboxID_RegistrarProd.SelectionStart = 0;
            this.txtboxID_RegistrarProd.ShortcutsEnabled = true;
            this.txtboxID_RegistrarProd.Size = new System.Drawing.Size(260, 31);
            this.txtboxID_RegistrarProd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtboxID_RegistrarProd.TabIndex = 18;
            this.txtboxID_RegistrarProd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtboxID_RegistrarProd.TextMarginBottom = 0;
            this.txtboxID_RegistrarProd.TextMarginLeft = 3;
            this.txtboxID_RegistrarProd.TextMarginTop = 1;
            this.txtboxID_RegistrarProd.TextPlaceholder = "Enter text";
            this.txtboxID_RegistrarProd.UseSystemPasswordChar = false;
            this.txtboxID_RegistrarProd.WordWrap = true;
            this.txtboxID_RegistrarProd.TextChanged += new System.EventHandler(this.txtboxID_RegistrarProd_TextChanged);
            // 
            // lblID_RegistrarProd
            // 
            this.lblID_RegistrarProd.AllowParentOverrides = false;
            this.lblID_RegistrarProd.AutoEllipsis = false;
            this.lblID_RegistrarProd.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblID_RegistrarProd.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblID_RegistrarProd.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblID_RegistrarProd.Location = new System.Drawing.Point(267, 60);
            this.lblID_RegistrarProd.Name = "lblID_RegistrarProd";
            this.lblID_RegistrarProd.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblID_RegistrarProd.Size = new System.Drawing.Size(17, 19);
            this.lblID_RegistrarProd.TabIndex = 19;
            this.lblID_RegistrarProd.Text = "ID";
            this.lblID_RegistrarProd.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblID_RegistrarProd.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lblID_RegistrarProd.Click += new System.EventHandler(this.lblID_RegistrarProd_Click);
            // 
            // btnCarcelar_Registroprod
            // 
            this.btnCarcelar_Registroprod.AllowAnimations = true;
            this.btnCarcelar_Registroprod.AllowMouseEffects = true;
            this.btnCarcelar_Registroprod.AllowToggling = false;
            this.btnCarcelar_Registroprod.AnimationSpeed = 200;
            this.btnCarcelar_Registroprod.AutoGenerateColors = false;
            this.btnCarcelar_Registroprod.AutoRoundBorders = true;
            this.btnCarcelar_Registroprod.AutoSizeLeftIcon = true;
            this.btnCarcelar_Registroprod.AutoSizeRightIcon = true;
            this.btnCarcelar_Registroprod.BackColor = System.Drawing.Color.Transparent;
            this.btnCarcelar_Registroprod.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCarcelar_Registroprod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCarcelar_Registroprod.BackgroundImage")));
            this.btnCarcelar_Registroprod.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarcelar_Registroprod.ButtonText = "Cancelar";
            this.btnCarcelar_Registroprod.ButtonTextMarginLeft = 0;
            this.btnCarcelar_Registroprod.ColorContrastOnClick = 45;
            this.btnCarcelar_Registroprod.ColorContrastOnHover = 45;
            this.btnCarcelar_Registroprod.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCarcelar_Registroprod.CustomizableEdges = borderEdges2;
            this.btnCarcelar_Registroprod.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCarcelar_Registroprod.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCarcelar_Registroprod.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCarcelar_Registroprod.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCarcelar_Registroprod.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCarcelar_Registroprod.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCarcelar_Registroprod.ForeColor = System.Drawing.Color.White;
            this.btnCarcelar_Registroprod.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCarcelar_Registroprod.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCarcelar_Registroprod.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCarcelar_Registroprod.IconMarginLeft = 11;
            this.btnCarcelar_Registroprod.IconPadding = 10;
            this.btnCarcelar_Registroprod.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCarcelar_Registroprod.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCarcelar_Registroprod.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCarcelar_Registroprod.IconSize = 25;
            this.btnCarcelar_Registroprod.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCarcelar_Registroprod.IdleBorderRadius = 36;
            this.btnCarcelar_Registroprod.IdleBorderThickness = 1;
            this.btnCarcelar_Registroprod.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCarcelar_Registroprod.IdleIconLeftImage = null;
            this.btnCarcelar_Registroprod.IdleIconRightImage = null;
            this.btnCarcelar_Registroprod.IndicateFocus = false;
            this.btnCarcelar_Registroprod.Location = new System.Drawing.Point(12, 400);
            this.btnCarcelar_Registroprod.Name = "btnCarcelar_Registroprod";
            this.btnCarcelar_Registroprod.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCarcelar_Registroprod.OnDisabledState.BorderRadius = 1;
            this.btnCarcelar_Registroprod.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarcelar_Registroprod.OnDisabledState.BorderThickness = 1;
            this.btnCarcelar_Registroprod.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCarcelar_Registroprod.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCarcelar_Registroprod.OnDisabledState.IconLeftImage = null;
            this.btnCarcelar_Registroprod.OnDisabledState.IconRightImage = null;
            this.btnCarcelar_Registroprod.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCarcelar_Registroprod.onHoverState.BorderRadius = 1;
            this.btnCarcelar_Registroprod.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarcelar_Registroprod.onHoverState.BorderThickness = 1;
            this.btnCarcelar_Registroprod.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCarcelar_Registroprod.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCarcelar_Registroprod.onHoverState.IconLeftImage = null;
            this.btnCarcelar_Registroprod.onHoverState.IconRightImage = null;
            this.btnCarcelar_Registroprod.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCarcelar_Registroprod.OnIdleState.BorderRadius = 1;
            this.btnCarcelar_Registroprod.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarcelar_Registroprod.OnIdleState.BorderThickness = 1;
            this.btnCarcelar_Registroprod.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCarcelar_Registroprod.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCarcelar_Registroprod.OnIdleState.IconLeftImage = null;
            this.btnCarcelar_Registroprod.OnIdleState.IconRightImage = null;
            this.btnCarcelar_Registroprod.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCarcelar_Registroprod.OnPressedState.BorderRadius = 1;
            this.btnCarcelar_Registroprod.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarcelar_Registroprod.OnPressedState.BorderThickness = 1;
            this.btnCarcelar_Registroprod.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCarcelar_Registroprod.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCarcelar_Registroprod.OnPressedState.IconLeftImage = null;
            this.btnCarcelar_Registroprod.OnPressedState.IconRightImage = null;
            this.btnCarcelar_Registroprod.Size = new System.Drawing.Size(73, 38);
            this.btnCarcelar_Registroprod.TabIndex = 20;
            this.btnCarcelar_Registroprod.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCarcelar_Registroprod.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCarcelar_Registroprod.TextMarginLeft = 0;
            this.btnCarcelar_Registroprod.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCarcelar_Registroprod.UseDefaultRadiusAndThickness = true;
            this.btnCarcelar_Registroprod.Click += new System.EventHandler(this.btnCarcelar_Registroprod_Click);
            // 
            // registrarProdutocs
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.btnCarcelar_Registroprod);
            this.Controls.Add(this.lblID_RegistrarProd);
            this.Controls.Add(this.txtboxID_RegistrarProd);
            this.Controls.Add(this.lblCategoria_Registroprod);
            this.Controls.Add(this.lblQntd_RegistroProd);
            this.Controls.Add(this.lblPreco_RegistroProd);
            this.Controls.Add(this.lblDescrição_RegistroProd);
            this.Controls.Add(this.lblNome_RegistroProd);
            this.Controls.Add(this.txtboxCategoria_registroProd);
            this.Controls.Add(this.txtboxQntd_RegistroProd);
            this.Controls.Add(this.txtboxPreco_RegistroProd);
            this.Controls.Add(this.txtboxDescricao_RegistroProd);
            this.Controls.Add(this.txtboxNome_RegistroProd);
            this.Controls.Add(this.btnEnviar_registroProd);
            this.Controls.Add(this.lbl_cadastrodeProd);
            this.Name = "registrarProdutocs";
            this.Text = "registrarProdutocs";
            this.Load += new System.EventHandler(this.registrarProdutocs_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel lbl_cadastrodeProd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEnviar_registroProd;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxNome_RegistroProd;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxDescricao_RegistroProd;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxPreco_RegistroProd;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxQntd_RegistroProd;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxCategoria_registroProd;
        private Bunifu.UI.WinForms.BunifuLabel lblNome_RegistroProd;
        private Bunifu.UI.WinForms.BunifuLabel lblDescrição_RegistroProd;
        private Bunifu.UI.WinForms.BunifuLabel lblPreco_RegistroProd;
        private Bunifu.UI.WinForms.BunifuLabel lblQntd_RegistroProd;
        private Bunifu.UI.WinForms.BunifuLabel lblCategoria_Registroprod;
        private Bunifu.UI.WinForms.BunifuTextBox txtboxID_RegistrarProd;
        private Bunifu.UI.WinForms.BunifuLabel lblID_RegistrarProd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCarcelar_Registroprod;
    }
}